//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Localizer.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Mod.Localizer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PathDesc {
            get {
                return ResourceManager.GetString("PathDesc", resourceCulture);
            }
        }
        
        internal static string ProgramModeDesc {
            get {
                return ResourceManager.GetString("ProgramModeDesc", resourceCulture);
            }
        }
        
        internal static string LanguageDesc {
            get {
                return ResourceManager.GetString("LanguageDesc", resourceCulture);
            }
        }
        
        internal static string NoFileSpecified {
            get {
                return ResourceManager.GetString("NoFileSpecified", resourceCulture);
            }
        }
        
        internal static string NoSourceFolderSpecified {
            get {
                return ResourceManager.GetString("NoSourceFolderSpecified", resourceCulture);
            }
        }
        
        internal static string PathArgumentName {
            get {
                return ResourceManager.GetString("PathArgumentName", resourceCulture);
            }
        }
        
        internal static string SourceFolderDesc {
            get {
                return ResourceManager.GetString("SourceFolderDesc", resourceCulture);
            }
        }
        
        internal static string DumpExceptionOccur {
            get {
                return ResourceManager.GetString("DumpExceptionOccur", resourceCulture);
            }
        }
        
        internal static string InvalidContent {
            get {
                return ResourceManager.GetString("InvalidContent", resourceCulture);
            }
        }
        
        internal static string PatchExceptionOccur {
            get {
                return ResourceManager.GetString("PatchExceptionOccur", resourceCulture);
            }
        }
        
        internal static string ProcessComplete {
            get {
                return ResourceManager.GetString("ProcessComplete", resourceCulture);
            }
        }
        
        internal static string ProcessTargetNullCheck {
            get {
                return ResourceManager.GetString("ProcessTargetNullCheck", resourceCulture);
            }
        }
        
        internal static string DumpNamespace {
            get {
                return ResourceManager.GetString("DumpNamespace", resourceCulture);
            }
        }
        
        internal static string InvalidGameCulture {
            get {
                return ResourceManager.GetString("InvalidGameCulture", resourceCulture);
            }
        }
        
        internal static string ProcExceptionOccur {
            get {
                return ResourceManager.GetString("ProcExceptionOccur", resourceCulture);
            }
        }
        
        internal static string ProcNotUsed {
            get {
                return ResourceManager.GetString("ProcNotUsed", resourceCulture);
            }
        }
        
        internal static string ProgramVersion {
            get {
                return ResourceManager.GetString("ProgramVersion", resourceCulture);
            }
        }
        
        internal static string Patching {
            get {
                return ResourceManager.GetString("Patching", resourceCulture);
            }
        }
        
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        internal static string BuildPropWrittenToPath {
            get {
                return ResourceManager.GetString("BuildPropWrittenToPath", resourceCulture);
            }
        }
        
        internal static string SourcePathDoesNotExist {
            get {
                return ResourceManager.GetString("SourcePathDoesNotExist", resourceCulture);
            }
        }
    }
}
